[package]
name = "l337-postgres"
version = "0.1.0"
authors = ["Jonathon Sheffield <samsmug@gmail.com>"]
edition = "2018"

[dependencies]
l337 = { path = ".." }
futures = "0.1"
tokio = "0.1"
tokio-postgres = { git = "https://github.com/sfackler/rust-postgres.git", rev = "e3f2eb72444e3b3fe75599bb660cb625cb9752df" }
