[package]
name = "l337-postgres"
version = "0.1.0"
authors = ["Jonathon Sheffield <samsmug@gmail.com>"]
edition = "2018"

[dependencies]
l337 = { path = ".." }
futures = "0.1"
tokio = "0.1"
tokio-postgres = { git = "https://github.com/sfackler/rust-postgres.git", rev = "dfc614bed1ce88b5a978f1ffcd7dfe5a39c19b10" }
