[package]
name = "l3-37"
version = "0.0.0"
authors = ["Jonathon Sheffield <samsmug@gmail.com>", "Joe Wilm <joe@jwilm.com>"]
license = "MIT OR Apache-2.0"
description = "yet another connection pooler"

[dependencies]
futures = "0.1.14"
tokio = "0.1.8"
crossbeam = "0.4"
