version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/rust:1.29
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          keys:
            - target-v1-{{ .Branch }}-{{ checksum "Cargo.lock" }}
            - target-v1-master-
            - target-v1-
      - run: cargo build --release
      - run: cargo test
      - save_cache:
          key: target-v1-{{ .Branch }}-{{ checksum "Cargo.lock" }}
          paths:
            - target/
